-- 0008_seed_exemplary_chuncheon.sql
-- 춘천 모범음식점 시드. import-exemplary-chuncheon.mjs 가 CSV 로부터 생성.
-- 0007(exemplary verification_type) 이 먼저 적용돼 있어야 한다.
--
-- 재실행 안전:
--   1) exemplary 인증 전부 삭제 (기존 centennial/good_price row 에 붙은 것 포함)
--   2) exemplary data_source row 삭제 (1번에서 verification 은 이미 정리됨)
--   3) 새로 INSERT
-- → 다른 인증(michelin/blue_ribbon/centennial/good_price)·다른 소스 행에는 영향 없음.
--
-- 매칭 결과: 매칭(A) 9곳 + 신규(C) 90곳 = 총 99개 모범음식점 인증.

delete from public.restaurant_verifications
 where verification_type_id = (select id from public.verification_types where code = 'exemplary');

delete from public.restaurants
 where sigungu = '춘천시' and data_source = 'exemplary';

insert into public.restaurants
  (name, address_road, latitude, longitude, sido, sigungu, phone,
   category_id, keywords, data_source, external_id, status)
values
  ('(주)원일유통 춘천(상)휴게소', '강원특별자치도 춘천시 동내면 영서로 1432', 37.812785, 127.766134, '강원특별자치도', '춘천시', '033-264-0500', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-주원일유통춘천상휴게소', 'published'),
  ('(주)춘천장어마을', '강원특별자치도 춘천시 구마니1길 36-11', 37.86878, 127.703933, '강원특별자치도', '춘천시', '033-253-4077', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-주춘천장어마을', 'published'),
  ('9우미닭갈비만천점', '강원특별자치도 춘천시 동면 만천로143번길 46-4, 1층', 37.879921, 127.761854, '강원특별자치도', '춘천시', '033-255-8422', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-9우미닭갈비만천점', 'published'),
  ('감미옥설렁탕', '강원특별자치도 춘천시 춘천로 217, 1층 (효자동)', 37.878024, 127.737863, '강원특별자치도', '춘천시', '033-256-3808', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-감미옥설렁탕', 'published'),
  ('강원한우타운', '강원특별자치도 춘천시 지석로 11, 별관동 3층 (퇴계동)', 37.853533, 127.737494, '강원특별자치도', '춘천시', '033-261-9253', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-강원한우타운', 'published'),
  ('강촌막국수', '강원특별자치도 춘천시 남산면 강촌로 62-1', 37.813242, 127.63359, '강원특별자치도', '춘천시', '033-262-9868', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-강촌막국수', 'published'),
  ('고미고미', '강원특별자치도 춘천시 근화길 15번길 17, 1층(근화동)', 37.872759, 127.717262, '강원특별자치도', '춘천시', '033-256-1562', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-고미고미', 'published'),
  ('거두정춘천거두리본점', '강원특별자치도 춘천시 동내면 춘천순환로 114', 37.856132, 127.756498, '강원특별자치도', '춘천시', '033-263-9291', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-거두정춘천거두리본점', 'published'),
  ('곰배령', '강원특별자치도 춘천시 춘천로 19, 1층 (온의동)', 37.866831, 127.721172, '강원특별자치도', '춘천시', '033-255-5500', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-곰배령', 'published'),
  ('공지천왕갈비', '강원특별자치도 춘천시 효자로 5 (퇴계동)', 37.865436, 127.725848, '강원특별자치도', '춘천시', '033-251-0791', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-공지천왕갈비', 'published'),
  ('구울래머글래', '강원특별자치도 춘천시 대양당길9번길 15(후평동)', 37.876814, 127.753736, '강원특별자치도', '춘천시', '033-242-3133', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-구울래머글래', 'published'),
  ('귀품찬곽만근숯불갈비(춘천점)', '강원특별자치도 춘천시 동내면 춘천순환로 65', 37.855977, 127.751191, '강원특별자치도', '춘천시', '033-263-9299', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-귀품찬곽만근숯불갈비춘천점', 'published'),
  ('그랑셰프(클럽하우스)', '강원특별자치도 춘천시 남산면 북한강변길 688', 37.830134, 127.578819, '강원특별자치도', '춘천시', '033-260-2760', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-그랑셰프클럽하우스', 'published'),
  ('금병산숯불철판닭갈비', '강원특별자치도 춘천시 신동면 금병의숙길 6 (1리)', 37.81643, 127.714852, '강원특별자치도', '춘천시', '033-262-4220', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-금병산숯불철판닭갈비', 'published'),
  ('꼬꼬메이플가든', '강원특별자치도 춘천시 동내면 동내로 195, 1,2층', 37.850318, 127.773346, '강원특별자치도', '춘천시', '033-261-2828', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-꼬꼬메이플가든', 'published'),
  ('나능이능이버섯백숙만천점', '강원특별자치도 춘천시 동면 만천로 94', 37.880962, 127.764147, '강원특별자치도', '춘천시', '033-257-9511', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-나능이능이버섯백숙만천점', 'published'),
  ('나능이능이버섯백숙춘천점', '강원특별자치도 춘천시 우묵길78번길 7, 1층 (퇴계동, 좌측)', 37.867505, 127.724533, '강원특별자치도', '춘천시', '033-241-4411', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-나능이능이버섯백숙춘천점', 'published'),
  ('남춘천명물닭갈비', '강원특별자치도 춘천시 충혼길5번길 3 (퇴계동)', 37.863349, 127.723583, '강원특별자치도', '춘천시', '033-254-9922', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-남춘천명물닭갈비', 'published'),
  ('누보', '강원특별자치도 춘천시 퇴계로 13, 3층 (퇴계동)', 37.866584, 127.723594, '강원특별자치도', '춘천시', '033-261-7570', (select id from public.categories where slug='japanese'), ARRAY['일식','춘천시'], 'exemplary', 'exemplary-춘천-누보', 'published'),
  ('대룡산닭갈비막국수', '강원특별자치도 춘천시 동내면 동내로 180, 1층', 37.8494671, 127.7716968, '강원특별자치도', '춘천시', '033-261-1421', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-대룡산닭갈비막국수', 'published'),
  ('대웅닭갈비막국수', '강원특별자치도 춘천시 동면 금옥길 5', 37.916777, 127.78272, '강원특별자치도', '춘천시', '033-241-2017', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-대웅닭갈비막국수', 'published'),
  ('더기운', '강원특별자치도 춘천시 동내면 거두길 18', 37.860422, 127.761518, '강원특별자치도', '춘천시', '033-256-0592', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-더기운', 'published'),
  ('더클래식', '강원특별자치도 춘천시 동내면 공지로 76', 37.854112, 127.751038, '강원특별자치도', '춘천시', '033-254-1900', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-더클래식', 'published'),
  ('델모니코스', '강원특별자치도 춘천시 동면 순환대로 1154-106, 1~2층', 37.892304, 127.777277, '강원특별자치도', '춘천시', '033-252-0999', (select id from public.categories where slug='western'), ARRAY['양식','춘천시'], 'exemplary', 'exemplary-춘천-델모니코스', 'published'),
  ('돈까스와 뼈다귀', '강원특별자치도 춘천시 충열로 282 (우두동)', 37.918106, 127.73986, '강원특별자치도', '춘천시', '033-251-5709', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-돈까스와뼈다귀', 'published'),
  ('동경', '강원특별자치도 춘천시 공지로 149, 3층 (석사동, 동진빌딩)', 37.859001, 127.745237, '강원특별자치도', '춘천시', '033-261-7555', (select id from public.categories where slug='japanese'), ARRAY['일식','춘천시'], 'exemplary', 'exemplary-춘천-동경', 'published'),
  ('동광한우프라자', '강원특별자치도 춘천시 춘천로170번길 5 (운교동)', 37.875986, 127.73338, '강원특별자치도', '춘천시', '033-262-3357', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-동광한우프라자', 'published'),
  ('동해막국수퇴계점', '강원특별자치도 춘천시 퇴계로 23 (퇴계동)', 37.866091, 127.724721, '강원특별자치도', '춘천시', '033-253-9259', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-동해막국수퇴계점', 'published'),
  ('돼지한마리(후평점)', '강원특별자치도 춘천시 후석로326번길 12, 2층 (후평동)', 37.880394, 127.750848, '강원특별자치도', '춘천시', '033-257-3895', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-돼지한마리후평점', 'published'),
  ('등촌 샤브 칼국수', '강원특별자치도 춘천시 금강로 32-1 (소양로3가, 169-2,180-1,180-2)', 37.881015, 127.725813, '강원특별자치도', '춘천시', '033-254-2594', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-등촌샤브칼국수', 'published'),
  ('뚜레', '강원특별자치도 춘천시 동내면 순환대로 643, 가동 1,2층', 37.880636, 127.725838, '강원특별자치도', '춘천시', '033-262-8838', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-뚜레', 'published'),
  ('마을회관', '강원특별자치도 춘천시 후석로 344번길 3', 37.881589, 127.748945, '강원특별자치도', '춘천시', '033-242-8891', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-마을회관', 'published'),
  ('만강', '강원특별자치도 춘천시 동내면 외솔길19번길 61', 37.857934, 127.756526, '강원특별자치도', '춘천시', '033-262-5900', (select id from public.categories where slug='japanese'), ARRAY['일식','춘천시'], 'exemplary', 'exemplary-춘천-만강', 'published'),
  ('명동명물닭갈비', '강원특별자치도 춘천시 금강로62번길 8, 1층 (조양동)', 37.879515, 127.727865, '강원특별자치도', '춘천시', '033-257-2961', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-명동명물닭갈비', 'published'),
  ('명동산골닭갈비', '강원특별자치도 춘천시 금강로62번길 7', 37.879371, 127.727945, '강원특별자치도', '춘천시', '033-257-9775', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-명동산골닭갈비', 'published'),
  ('명동일번지닭갈비', '강원특별자치도 춘천시 금강로62번길 7 (조양동, 외8필지)', 37.879371, 127.727945, '강원특별자치도', '춘천시', '033-254-7042', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-명동일번지닭갈비', 'published'),
  ('별당막국수', '강원특별자치도 춘천시 춘천로81번길 15, 1층 (약사동)', 37.872082, 127.724289, '강원특별자치도', '춘천시', '033-254-9603', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-별당막국수', 'published'),
  ('보영이네해물칼국수만천리점', '강원특별자치도 춘천시 만천로145', 37.882447, 127.758537, '강원특별자치도', '춘천시', '033-257-0883', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-보영이네해물칼국수만천리점', 'published'),
  ('본관남부막국수', '강원특별자치도 춘천시 춘천로81번길 16, 1,2층 (약사동)', 37.872298, 127.724357, '강원특별자치도', '춘천시', '033-254-7859', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-본관남부막국수', 'published'),
  ('봄담은산채', '강원특별자치도 춘천시 선들길 38, 1층(삼천동)', 37.866038, 127.725266, '강원특별자치도', '춘천시', '033-252-5313', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-봄담은산채', 'published'),
  ('봉운장', '강원특별자치도 춘천시 소양고개길 26 (소양로3가)', 37.883573, 127.725565, '강원특별자치도', '춘천시', '033-254-3203', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-봉운장', 'published'),
  ('부안막국수', '강원특별자치도 춘천시 후석로344번길 7 (후평동)', 37.881797, 127.749456, '강원특별자치도', '춘천시', '033-254-0654', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-부안막국수', 'published'),
  ('부안옥', '강원특별자치도 춘천시 보안길 58, 1층 (후평동)', 37.879809, 127.751123, '강원특별자치도', '춘천시', '033-256-5252', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-부안옥', 'published'),
  ('비와별닭갈비본점', '강원특별자치도 춘천시 스무숲길 5 (석사동, 1,2층)', 37.849846, 127.749041, '강원특별자치도', '춘천시', '033-262-8899', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-비와별닭갈비본점', 'published'),
  ('샘토숯불닭갈비남춘천역점', '강원특별자치도 춘천시 우묵길52번길 10 (퇴계동)', 37.864934, 127.72294, '강원특별자치도', '춘천시', '033-255-5211', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-샘토숯불닭갈비남춘천역점', 'published'),
  ('샤브향', '강원특별자치도 춘천시 동내면 외솔길19번길 64-8', 37.857232, 127.756858, '강원특별자치도', '춘천시', '033-263-2555', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-샤브향', 'published'),
  ('샤브향(퇴계점)', '강원특별자치도 춘천시 우묵들길 35-6, 1층 (퇴계동)', 37.867615, 127.725079, '강원특별자치도', '춘천시', '033-252-2868', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-샤브향퇴계점', 'published'),
  ('성우닭갈비', '강원특별자치도 춘천시 동내면 춘천순환로 110', 37.856095, 127.756066, '강원특별자치도', '춘천시', '033-244-5579', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-성우닭갈비', 'published'),
  ('소담송하앤드더나인피크', '강원특별자치도 춘천시 동면 춘천순환로 868, 1~2층', 37.891979, 127.749479, '강원특별자치도', '춘천시', '033-257-1005', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-소담송하앤드더나인피크', 'published'),
  ('소양강양어장', '강원특별자치도 춘천시 동면 소양강로 675 (외1필지)', 37.925056, 127.781842, '강원특별자치도', '춘천시', '033-242-1002', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-소양강양어장', 'published'),
  ('순대박사', '강원특별자치도 춘천시 영서로 2502(근화동)', 37.881193, 127.713774, '강원특별자치도', '춘천시', '033-244-6660', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-순대박사', 'published'),
  ('시골막국수', '강원특별자치도 춘천시 신북읍 율문길 100', 37.924702, 127.748686, '강원특별자치도', '춘천시', '033-242-6833', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-시골막국수', 'published'),
  ('아보카도', '강원특별자치도 춘천시 약사고개길50번길 25, 2층 (약사동)', 37.872936, 127.725205, '강원특별자치도', '춘천시', '033-242-8188', (select id from public.categories where slug='western'), ARRAY['양식','춘천시'], 'exemplary', 'exemplary-춘천-아보카도', 'published'),
  ('연산골막국수', '강원특별자치도 춘천시 동면 연산골길 105-12', 37.897491, 127.790258, '강원특별자치도', '춘천시', '033-241-7025', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-연산골막국수', 'published'),
  ('오부자닭갈비막국수', '강원특별자치도 춘천시 안마산로 22 (온의동)', 37.858409, 127.718749, '강원특별자치도', '춘천시', '033-252-2311', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-오부자닭갈비막국수', 'published'),
  ('우성닭갈비본점', '강원특별자치도 춘천시 동면 만천양지길 87', 37.887331, 127.763501, '강원특별자치도', '춘천시', '033-242-3833', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-우성닭갈비본점', 'published'),
  ('원조갈비탕', '강원특별자치도 춘천시 시청길 32, 1층 110호 (조양동)', 37.881045, 127.731134, '강원특별자치도', '춘천시', '033-241-8882', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-원조갈비탕', 'published'),
  ('원주토정추어탕', '강원특별자치도 춘천시 신동면 김유정로 1746', 37.842924, 127.731783, '강원특별자치도', '춘천시', '033-256-9888', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-원주토정추어탕', 'published'),
  ('유미닭갈비', '강원특별자치도 춘천시 금강로62번길 12 (조양동)', 37.879216, 127.727434, '강원특별자치도', '춘천시', '033-252-4986', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-유미닭갈비', 'published'),
  ('유포리막국수', '강원특별자치도 춘천시 신북읍 맥국2길 123 (외2필지)', 37.946079, 127.77831, '강원특별자치도', '춘천시', '033-242-5168', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-유포리막국수', 'published'),
  ('육쌈냉면(춘천명동점)', '강원특별자치도 춘천시 명동길 9 (조양동)', 37.879505, 127.727604, '강원특별자치도', '춘천시', '033-254-4198', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-육쌈냉면춘천명동점', 'published'),
  ('은담숯불닭갈비', '강원특별자치도 춘천시 남산면 한치로 62, 1층', 37.7923808, 127.6447613, '강원특별자치도', '춘천시', '033-262-0209', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-은담숯불닭갈비', 'published'),
  ('이비가짬뽕춘천점', '강원특별자치도 춘천시 영서로 2652, 2층 (근화동)', 37.892567, 127.722508, '강원특별자치도', '춘천시', '033-242-9888', (select id from public.categories where slug='chinese'), ARRAY['중식','춘천시'], 'exemplary', 'exemplary-춘천-이비가짬뽕춘천점', 'published'),
  ('일점오닭갈비', '강원특별자치도 춘천시 후만로 77 (후평동)', 37.876353, 127.753135, '강원특별자치도', '춘천시', '033-253-8635', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-일점오닭갈비', 'published'),
  ('장호더그릴', '강원특별자치도 춘천시 신북읍 신샘밭로 682, 1~2층', 37.929424, 127.785344, '강원특별자치도', '춘천시', '033-243-9293', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-장호더그릴', 'published'),
  ('정자나루', '강원특별자치도 춘천시 남산면 한치로 120', 37.787675, 127.647204, '강원특별자치도', '춘천시', '033-264-7002', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-정자나루', 'published'),
  ('정족리동치미막국수', '강원특별자치도 춘천시 신동면 김유정로 1772, 1층', 37.845457, 127.732478, '강원특별자치도', '춘천시', '0507-1339-1189', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-정족리동치미막국수', 'published'),
  ('조약돌숯불닭갈비', '강원특별자치도 춘천시 낙원길 43 (낙원동, 1층)', 37.880034, 127.726431, '강원특별자치도', '춘천시', '033-264-0858', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-조약돌숯불닭갈비', 'published'),
  ('중화루', '강원특별자치도 춘천시 둥지길 5-17, 2,3층 (효자동)', 37.875541, 127.735769, '강원특별자치도', '춘천시', '033-254-2591', (select id from public.categories where slug='chinese'), ARRAY['중식','춘천시'], 'exemplary', 'exemplary-춘천-중화루', 'published'),
  ('춘천명종닭갈비&교동면옥', '강원특별자치도 춘천시 동면 도일길 56, 1,2층', 37.884541, 127.765147, '강원특별자치도', '춘천시', '033-241-0599', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-춘천명종닭갈비&교동면옥', 'published'),
  ('춘천사랑닭갈비', '강원특별자치도 춘천시 낙원길 47-1 (낙원동)', 37.880368, 127.726623, '강원특별자치도', '춘천시', '033-256-9211', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-춘천사랑닭갈비', 'published'),
  ('춘천산닭산속에닭갈비', '강원특별자치도 춘천시 옛경춘로 562-20, 가,나동 1층 (온의동)', 37.851533, 127.714206, '강원특별자치도', '춘천시', '033-242-8895', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-춘천산닭산속에닭갈비', 'published'),
  ('춘천원조숯불닭갈비', '강원특별자치도 춘천시 효자로 9 (퇴계동)', 37.865807, 127.726336, '강원특별자치도', '춘천시', '033-253-9253', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-춘천원조숯불닭갈비', 'published'),
  ('춘천이동갈비', '강원특별자치도 춘천시 춘주로201번길 4, 1층 (퇴계동)', 37.861079, 127.727762, '강원특별자치도', '춘천시', '033-243-0100', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-춘천이동갈비', 'published'),
  ('춘천제일닭갈비', '강원특별자치도 춘천시 새롬공원길 22-1, 1층 (석사동)', 37.85432, 127.747481, '강원특별자치도', '춘천시', '033-263-9399', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-춘천제일닭갈비', 'published'),
  ('콩사랑마을', '강원특별자치도 춘천시 우묵들길 35-14 (퇴계동)', 37.867856, 127.724362, '강원특별자치도', '춘천시', '033-255-2180', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-콩사랑마을', 'published'),
  ('큰샛터막국수', '강원특별자치도 춘천시 동내면 영서로 1745-14, 1층', 37.8327147, 127.601563, '강원특별자치도', '춘천시', '033-262-4733', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-큰샛터막국수', 'published'),
  ('큰집한우', '강원특별자치도 춘천시 서부대성로 135, 2층 (운교동)', 37.877864, 127.734976, '강원특별자치도', '춘천시', '033-241-3944', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-큰집한우', 'published'),
  ('토담화로구이', '강원특별자치도 춘천시 남춘로36번길 65 (퇴계동, 1층)', 37.860398, 127.737061, '강원특별자치도', '춘천시', '033-263-7799', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-토담화로구이', 'published'),
  ('하주골', '강원특별자치도 춘천시 동면 만천로 163', 37.883416, 127.756636, '강원특별자치도', '춘천시', '033-256-7963', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-하주골', 'published'),
  ('학곡리막국수닭갈비', '강원특별자치도 춘천시 공지로 29, 1층 (석사동)', 37.850313, 127.752994, '강원특별자치도', '춘천시', '033-261-9478', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-학곡리막국수닭갈비', 'published'),
  ('한양시래기명태조림춘천점', '강원특별자치도 춘천시 영서로 2195 (퇴계동, (굿모닝마트2층))', 37.860297, 127.728572, '강원특별자치도', '춘천시', '033-256-8886', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-한양시래기명태조림춘천점', 'published'),
  ('한우가', '강원특별자치도 춘천시 스무숲3길 18, 1.2동 1층 (석사동)', 37.84767, 127.751196, '강원특별자치도', '춘천시', '033-261-2621', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-한우가', 'published'),
  ('함지', '강원특별자치도 춘천시 중앙로 101 (중앙로3가)', 37.877118, 127.723816, '강원특별자치도', '춘천시', '033-254-5221', (select id from public.categories where slug='western'), ARRAY['양식','춘천시'], 'exemplary', 'exemplary-춘천-함지', 'published'),
  ('항아리닭갈비막국수', '강원특별자치도 춘천시 신북읍 신샘밭로 487', 37.930292, 127.763603, '강원특별자치도', '춘천시', '033-242-1411', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-항아리닭갈비막국수', 'published'),
  ('형제육회', '강원특별자치도 춘천시 스무숲길 34, 1층 (석사동)', 37.848264, 127.751308, '강원특별자치도', '춘천시', '033-256-4719', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-형제육회', 'published'),
  ('호반', '강원특별자치도 춘천시 스포츠타운길 376, 1층 (삼천동)', 37.870894, 127.699071, '강원특별자치도', '춘천시', '033-245-4300', null, ARRAY['뷔페식','춘천시'], 'exemplary', 'exemplary-춘천-호반', 'published'),
  ('황가네', '강원특별자치도 춘천시 충혼길5번길 9-1 (퇴계동, 1층)', 37.863008, 127.724221, '강원특별자치도', '춘천시', '033-254-6692', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-황가네', 'published'),
  ('회,장,메', '강원특별자치도 춘천시 화목원길 21 (사농동)', 37.923935, 127.723767, '강원특별자치도', '춘천시', '033-255-2521', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-회장메', 'published'),
  ('효자황태구이', '강원특별자치도 춘천시 남춘로51번길 15-1 (효자동, 1~2층)', 37.86598, 127.731143, '강원특별자치도', '춘천시', '033-253-9988', (select id from public.categories where slug='korean'), ARRAY['한식','춘천시'], 'exemplary', 'exemplary-춘천-효자황태구이', 'published');

insert into public.restaurant_verifications
  (restaurant_id, verification_type_id, awarded_year, is_verified, metadata)
select r.id, vt.id, v.year, true, v.metadata
from (values
  ('exemplary'::text, 'exemplary-춘천-주원일유통춘천상휴게소'::text, 2024::int, '{"primary_menu":"순두부찌개, 닭갈비","seating":"입식","wheelchair_accessible":true}'::jsonb),
  ('exemplary', 'exemplary-춘천-주춘천장어마을', 2024, '{"primary_menu":"장어요리전문","seating":"입식","wheelchair_accessible":false}'::jsonb),
  ('exemplary', 'exemplary-춘천-9우미닭갈비만천점', 2024, '{"primary_menu":"닭갈비,막국수","seating":"둘다","wheelchair_accessible":true}'::jsonb),
  ('exemplary', 'exemplary-춘천-감미옥설렁탕', 2024, '{"primary_menu":"설렁탕","seating":"입식","wheelchair_accessible":true}'::jsonb),
  ('exemplary', 'exemplary-춘천-강원한우타운', 2024, '{"primary_menu":"한우전문점","seating":"좌식","wheelchair_accessible":true}'::jsonb),
  ('exemplary', 'exemplary-춘천-강촌막국수', 2024, '{"primary_menu":"막국수,편육","seating":"둘다","wheelchair_accessible":true}'::jsonb),
  ('exemplary', 'exemplary-춘천-고미고미', 2024, '{"primary_menu":"생선구이","seating":"입식","wheelchair_accessible":true}'::jsonb),
  ('exemplary', 'exemplary-춘천-거두정춘천거두리본점', 2024, '{"primary_menu":"삼겹살, 목살","seating":"입식","wheelchair_accessible":true}'::jsonb),
  ('exemplary', 'exemplary-춘천-곰배령', 2024, '{"primary_menu":"한정식","seating":"둘다","wheelchair_accessible":false}'::jsonb),
  ('exemplary', 'exemplary-춘천-공지천왕갈비', 2024, '{"primary_menu":"갈비","seating":"좌식","wheelchair_accessible":false}'::jsonb),
  ('exemplary', 'exemplary-춘천-구울래머글래', 2024, '{"primary_menu":"생삼겹살, 생갈매기살","seating":"입식","wheelchair_accessible":false}'::jsonb),
  ('exemplary', 'exemplary-춘천-귀품찬곽만근숯불갈비춘천점', 2024, '{"primary_menu":"숯불갈비","seating":"입식","wheelchair_accessible":false}'::jsonb),
  ('exemplary', 'exemplary-춘천-그랑셰프클럽하우스', 2024, '{"primary_menu":"유황오리백숙,우거지해장국","seating":"입식","wheelchair_accessible":true}'::jsonb),
  ('exemplary', 'exemplary-춘천-금병산숯불철판닭갈비', 2024, '{"primary_menu":"닭갈비,막국수","seating":"둘다","wheelchair_accessible":false}'::jsonb),
  ('exemplary', 'exemplary-춘천-꼬꼬메이플가든', 2024, '{"primary_menu":"닭갈비, 막국수","seating":"입식","wheelchair_accessible":true}'::jsonb),
  ('exemplary', 'exemplary-춘천-나능이능이버섯백숙만천점', 2024, '{"primary_menu":"오리, 닭백숙","seating":"둘다","wheelchair_accessible":true}'::jsonb),
  ('exemplary', 'exemplary-춘천-나능이능이버섯백숙춘천점', 2024, '{"primary_menu":"능이버섯백숙","seating":"둘다","wheelchair_accessible":true}'::jsonb),
  ('exemplary', 'exemplary-춘천-남춘천명물닭갈비', 2024, '{"primary_menu":"닭갈비","seating":"입식","wheelchair_accessible":false}'::jsonb),
  ('exemplary', 'exemplary-춘천-누보', 2024, '{"primary_menu":"회코스","seating":"좌식","wheelchair_accessible":true}'::jsonb),
  ('exemplary', 'exemplary-춘천-대룡산닭갈비막국수', 2024, '{"primary_menu":"막국수,닭갈비","seating":"입식","wheelchair_accessible":true}'::jsonb),
  ('exemplary', 'exemplary-춘천-대웅닭갈비막국수', 2024, '{"primary_menu":"닭갈비","seating":"좌식","wheelchair_accessible":false}'::jsonb),
  ('exemplary', 'exemplary-춘천-더기운', 2024, '{"primary_menu":"장어","seating":"입식","wheelchair_accessible":true}'::jsonb),
  ('exemplary', 'exemplary-춘천-더클래식', 2024, '{"primary_menu":"뷔페","seating":"좌식","wheelchair_accessible":true}'::jsonb),
  ('exemplary', 'exemplary-춘천-델모니코스', 2024, '{"primary_menu":"경양식전문점","seating":"입식","wheelchair_accessible":true}'::jsonb),
  ('exemplary', 'exemplary-춘천-돈까스와뼈다귀', 2024, '{"primary_menu":"돈까스,뼈다귀해장국","seating":"좌식","wheelchair_accessible":false}'::jsonb),
  ('exemplary', 'exemplary-춘천-동경', 2024, '{"primary_menu":"회정식","seating":"좌식","wheelchair_accessible":false}'::jsonb),
  ('exemplary', 'exemplary-춘천-동광한우프라자', 2024, '{"primary_menu":"등심,갈비탕","seating":"좌식","wheelchair_accessible":false}'::jsonb),
  ('exemplary', 'exemplary-춘천-동해막국수퇴계점', 2024, '{"primary_menu":"막국수, 족발","seating":"둘다","wheelchair_accessible":true}'::jsonb),
  ('exemplary', 'exemplary-춘천-돼지한마리후평점', 2024, '{"primary_menu":"돼지갈비, 삼겹살","seating":"좌식","wheelchair_accessible":false}'::jsonb),
  ('exemplary', 'exemplary-춘천-등촌샤브칼국수', 2024, '{"primary_menu":"샤브칼국수","seating":"입식","wheelchair_accessible":false}'::jsonb),
  ('exemplary', 'exemplary-춘천-뚜레', 2024, '{"primary_menu":"등심,정육","seating":"입식","wheelchair_accessible":true}'::jsonb),
  ('exemplary', 'exemplary-춘천-마을회관', 2024, '{"primary_menu":"모듬회, 광어회","seating":"입식","wheelchair_accessible":false}'::jsonb),
  ('exemplary', 'exemplary-춘천-만강', 2024, '{"primary_menu":"정식,생선회","seating":"좌식","wheelchair_accessible":false}'::jsonb),
  ('exemplary', 'exemplary-춘천-명동명물닭갈비', 2024, '{"primary_menu":"닭갈비","seating":"둘다","wheelchair_accessible":false}'::jsonb),
  ('exemplary', 'exemplary-춘천-명동산골닭갈비', 2024, '{"primary_menu":"닭갈비","seating":"둘다","wheelchair_accessible":true}'::jsonb),
  ('exemplary', 'exemplary-춘천-명동일번지닭갈비', 2024, '{"primary_menu":"닭갈비,막국수","seating":"둘다","wheelchair_accessible":true}'::jsonb),
  ('exemplary', 'exemplary-춘천-별당막국수', 2024, '{"primary_menu":"막국수,편육","seating":"둘다","wheelchair_accessible":true}'::jsonb),
  ('exemplary', 'exemplary-춘천-보영이네해물칼국수만천리점', 2024, '{"primary_menu":"칼국수","seating":"좌식","wheelchair_accessible":false}'::jsonb),
  ('exemplary', 'exemplary-춘천-본관남부막국수', 2024, '{"primary_menu":"막국수,편육,빈대떡","seating":"둘다","wheelchair_accessible":true}'::jsonb),
  ('exemplary', 'exemplary-춘천-봄담은산채', 2024, '{"primary_menu":"한정식","seating":"입식","wheelchair_accessible":true}'::jsonb),
  ('exemplary', 'exemplary-춘천-봉운장', 2024, '{"primary_menu":"갈비,갈비탕","seating":"입식","wheelchair_accessible":true}'::jsonb),
  ('exemplary', 'exemplary-춘천-부안막국수', 2024, '{"primary_menu":"막국수","seating":"둘다","wheelchair_accessible":false}'::jsonb),
  ('exemplary', 'exemplary-춘천-부안옥', 2024, '{"primary_menu":"소갈비살, 삼겹살","seating":"둘다","wheelchair_accessible":false}'::jsonb),
  ('exemplary', 'exemplary-춘천-비와별닭갈비본점', 2024, '{"primary_menu":"닭갈비","seating":"입식","wheelchair_accessible":false}'::jsonb),
  ('exemplary', 'exemplary-춘천-샘토숯불닭갈비남춘천역점', 2024, '{"primary_menu":"숯불닭갈비","seating":"좌식","wheelchair_accessible":true}'::jsonb),
  ('exemplary', 'exemplary-춘천-샤브향', 2024, '{"primary_menu":"월남쌈,소고기샤브","seating":"둘다","wheelchair_accessible":true}'::jsonb),
  ('exemplary', 'exemplary-춘천-샤브향퇴계점', 2024, '{"primary_menu":"샤브샤브","seating":"둘다","wheelchair_accessible":true}'::jsonb),
  ('exemplary', 'exemplary-춘천-성우닭갈비', 2024, '{"primary_menu":"닭갈비","seating":"둘다","wheelchair_accessible":true}'::jsonb),
  ('exemplary', 'exemplary-춘천-소담송하앤드더나인피크', 2024, '{"primary_menu":"돼지갈비","seating":"입식","wheelchair_accessible":false}'::jsonb),
  ('exemplary', 'exemplary-춘천-소양강양어장', 2024, '{"primary_menu":"송어.산천어","seating":"둘다","wheelchair_accessible":true}'::jsonb),
  ('exemplary', 'exemplary-춘천-순대박사', 2024, '{"primary_menu":"사골순대국밥","seating":"입식","wheelchair_accessible":false}'::jsonb),
  ('exemplary', 'exemplary-춘천-시골막국수', 2024, '{"primary_menu":"막국수","seating":"입식","wheelchair_accessible":true}'::jsonb),
  ('exemplary', 'exemplary-춘천-아보카도', 2024, '{"primary_menu":"스테이크, 샐러드","seating":"입식","wheelchair_accessible":false}'::jsonb),
  ('exemplary', 'exemplary-춘천-연산골막국수', 2024, '{"primary_menu":"막국수, 수육","seating":"입식","wheelchair_accessible":true}'::jsonb),
  ('exemplary', 'exemplary-춘천-오부자닭갈비막국수', 2024, '{"primary_menu":"닭갈비,막국수","seating":"둘다","wheelchair_accessible":true}'::jsonb),
  ('exemplary', 'exemplary-춘천-우성닭갈비본점', 2024, '{"primary_menu":"닭갈비","seating":"입식","wheelchair_accessible":true}'::jsonb),
  ('exemplary', 'exemplary-춘천-원조갈비탕', 2024, '{"primary_menu":"갈비탕","seating":"입식","wheelchair_accessible":true}'::jsonb),
  ('exemplary', 'exemplary-춘천-원주토정추어탕', 2024, '{"primary_menu":"추어탕","seating":"둘다","wheelchair_accessible":true}'::jsonb),
  ('exemplary', 'exemplary-춘천-유미닭갈비', 2024, '{"primary_menu":"닭갈비","seating":"둘다","wheelchair_accessible":false}'::jsonb),
  ('exemplary', 'exemplary-춘천-유포리막국수', 2024, '{"primary_menu":"막국수","seating":"둘다","wheelchair_accessible":true}'::jsonb),
  ('exemplary', 'exemplary-춘천-육쌈냉면춘천명동점', 2024, '{"primary_menu":"냉면","seating":"입식","wheelchair_accessible":false}'::jsonb),
  ('exemplary', 'exemplary-춘천-은담숯불닭갈비', 2024, '{"primary_menu":"숯불양념삽겹살,숯불닭갈비","seating":"둘다","wheelchair_accessible":true}'::jsonb),
  ('exemplary', 'exemplary-춘천-이비가짬뽕춘천점', 2024, '{"primary_menu":"짬뽕,탕수육","seating":"둘다","wheelchair_accessible":true}'::jsonb),
  ('exemplary', 'exemplary-춘천-일점오닭갈비', 2024, '{"primary_menu":"닭갈비","seating":"둘다","wheelchair_accessible":false}'::jsonb),
  ('exemplary', 'exemplary-춘천-장호더그릴', 2024, '{"primary_menu":"닭갈비","seating":"입식","wheelchair_accessible":true}'::jsonb),
  ('exemplary', 'exemplary-춘천-정자나루', 2024, '{"primary_menu":"오리백숙,닭백숙","seating":"입식","wheelchair_accessible":true}'::jsonb),
  ('exemplary', 'exemplary-춘천-정족리동치미막국수', 2024, '{"primary_menu":"동치미막국수, 편육","seating":"입식","wheelchair_accessible":true}'::jsonb),
  ('exemplary', 'exemplary-춘천-조약돌숯불닭갈비', 2024, '{"primary_menu":"닭갈비","seating":"좌식","wheelchair_accessible":false}'::jsonb),
  ('exemplary', 'exemplary-춘천-중화루', 2024, '{"primary_menu":"탕수육, 자장면","seating":"입식","wheelchair_accessible":true}'::jsonb),
  ('exemplary', 'exemplary-춘천-춘천명종닭갈비&교동면옥', 2024, '{"primary_menu":"닭갈비","seating":"입식","wheelchair_accessible":true}'::jsonb),
  ('exemplary', 'exemplary-춘천-춘천사랑닭갈비', 2024, '{"primary_menu":"닭갈비,막국수","seating":"좌식","wheelchair_accessible":true}'::jsonb),
  ('exemplary', 'exemplary-춘천-춘천산닭산속에닭갈비', 2024, '{"primary_menu":"닭갈비","seating":"둘다","wheelchair_accessible":true}'::jsonb),
  ('exemplary', 'exemplary-춘천-춘천원조숯불닭갈비', 2024, '{"primary_menu":"숯불닭갈비","seating":"좌식","wheelchair_accessible":false}'::jsonb),
  ('exemplary', 'exemplary-춘천-춘천이동갈비', 2024, '{"primary_menu":"이동갈비","seating":"입식","wheelchair_accessible":false}'::jsonb),
  ('exemplary', 'exemplary-춘천-춘천제일닭갈비', 2024, '{"primary_menu":"닭갈비","seating":"둘다","wheelchair_accessible":true}'::jsonb),
  ('exemplary', 'exemplary-춘천-콩사랑마을', 2024, '{"primary_menu":"두부전골","seating":"좌식","wheelchair_accessible":false}'::jsonb),
  ('exemplary', 'exemplary-춘천-큰샛터막국수', 2024, '{"primary_menu":"막국수","seating":"입식","wheelchair_accessible":true}'::jsonb),
  ('exemplary', 'exemplary-춘천-큰집한우', 2024, '{"primary_menu":"등심, 육회","seating":"둘다","wheelchair_accessible":true}'::jsonb),
  ('exemplary', 'exemplary-춘천-토담화로구이', 2024, '{"primary_menu":"돼지갈비","seating":"좌식","wheelchair_accessible":false}'::jsonb),
  ('exemplary', 'exemplary-춘천-하주골', 2024, '{"primary_menu":"한정식","seating":"둘다","wheelchair_accessible":true}'::jsonb),
  ('exemplary', 'exemplary-춘천-학곡리막국수닭갈비', 2024, '{"primary_menu":"막국수,닭갈비","seating":"입식","wheelchair_accessible":true}'::jsonb),
  ('exemplary', 'exemplary-춘천-한양시래기명태조림춘천점', 2024, '{"primary_menu":"육개장, 시래기명태조림","seating":"둘다","wheelchair_accessible":true}'::jsonb),
  ('exemplary', 'exemplary-춘천-한우가', 2024, '{"primary_menu":"갈비살,살치살","seating":"입식","wheelchair_accessible":false}'::jsonb),
  ('exemplary', 'exemplary-춘천-함지', 2024, '{"primary_menu":"양식","seating":"입식","wheelchair_accessible":false}'::jsonb),
  ('exemplary', 'exemplary-춘천-항아리닭갈비막국수', 2024, '{"primary_menu":"닭갈비","seating":"입식","wheelchair_accessible":true}'::jsonb),
  ('exemplary', 'exemplary-춘천-형제육회', 2024, '{"primary_menu":"모듬육회, 육회비빔밥","seating":"입식","wheelchair_accessible":false}'::jsonb),
  ('exemplary', 'exemplary-춘천-호반', 2024, '{"primary_menu":"뷔페","seating":"입식","wheelchair_accessible":true}'::jsonb),
  ('exemplary', 'exemplary-춘천-황가네', 2024, '{"primary_menu":"등심,소갈비살","seating":"좌식","wheelchair_accessible":false}'::jsonb),
  ('exemplary', 'exemplary-춘천-회장메', 2024, '{"primary_menu":"민물회","seating":"입식","wheelchair_accessible":false}'::jsonb),
  ('exemplary', 'exemplary-춘천-효자황태구이', 2024, '{"primary_menu":"황태구이","seating":"입식","wheelchair_accessible":false}'::jsonb),
  ('good_price', 'good_price-춘천-금옥', 2024, '{"primary_menu":"막국수, 돼지곰탕","seating":"입식","wheelchair_accessible":true}'::jsonb),
  ('centennial', 'centennial-춘천-메바우명가춘천막국수', 2024, '{"primary_menu":"막국수, 편육","seating":"둘다","wheelchair_accessible":false}'::jsonb),
  ('centennial', 'centennial-춘천-주식회사명가막국수', 2024, '{"primary_menu":"막국수","seating":"둘다","wheelchair_accessible":true}'::jsonb),
  ('centennial', 'centennial-춘천-샘밭막국수', 2024, '{"primary_menu":"막국수","seating":"둘다","wheelchair_accessible":true}'::jsonb),
  ('centennial', 'centennial-춘천-오수물막국수', 2024, '{"primary_menu":"막국수,보쌈","seating":"둘다","wheelchair_accessible":true}'::jsonb),
  ('good_price', 'good_price-춘천-임가네', 2024, '{"primary_menu":"고기말이, 등심","seating":"입식","wheelchair_accessible":false}'::jsonb),
  ('centennial', 'centennial-춘천-주식회사통나무집닭갈비', 2024, '{"primary_menu":"닭갈비","seating":"입식","wheelchair_accessible":true}'::jsonb),
  ('good_price', 'good_price-춘천-해미담', 2024, '{"primary_menu":"생삼겹살","seating":"둘다","wheelchair_accessible":true}'::jsonb),
  ('good_price', 'good_price-춘천-황토집', 2024, '{"primary_menu":"한정식","seating":"입식","wheelchair_accessible":false}'::jsonb)
) as v(source, ext_id, year, metadata)
join public.restaurants r on r.data_source = v.source and r.external_id = v.ext_id
join public.verification_types vt on vt.code = 'exemplary';
